import Head from 'next/head'
import Image from 'next/image'
import {motion} from "framer-motion";
import styled from "styled-components";
import { useEffect } from 'react';

const MainContainer = styled.div`
    min-height: 150vh;
    margin-top: 60px;
    color: white;
    background: #1A1A29;
   

`;


export default function Home({page,setPage}) {

  useEffect(()=>{
    setPage(1);
  },[])


  return (
    <>
      <Head>
        <title>Portfolio Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer>
          About Me Page
      </MainContainer>
    </>
  )
}
